# Generated by Django 3.0 on 2021-10-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('selectzones', models.CharField(max_length=100)),
                ('selectlanes', models.CharField(max_length=100)),
                ('audio_src', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('img_src', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grievance_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grievance',
                'managed': False,
            },
        ),
    ]
